[package]
name = "montelibero-transactions"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.26"
sha2 = "0.9.5"
hex-literal = "0.3.3"

[dependencies.substrate-stellar-sdk]
# path = "../../substrate-stellar-sdk"
git = "https://github.com/ncrashed/substrate-stellar-sdk"
revision = "9ed5ddb6521ce70ec4ccba08a2b83e7736f8870c"
features = [ "offchain", "all-types" ]