CREATE TABLE transactions (
  id TEXT NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL,
  description TEXT NOT NULL,
  body BLOB NOT NULL, 
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaction_updates (
  id INTEGER  NOT NULL PRIMARY KEY, 
  txid TEXT NOT NULL,
  body BLOB NOT NULL, 
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY(txid) REFERENCES transactions(id)
);